### ISSUE TITLE
i cant get this to work keep geting errors in console if you have a discord pepole can use to talk or help each other please let me know it .. or please help me ... 

### ISSUE THREAD

**Issue by James-the-Coding-Gamer** [zellfrey/Voting#1]
i cant get this to work keep geting errors in console if you have a discord pepole can use to talk or help each other please let me know it .. or please help me ...  my discord name is Real Stoner Gamer#3832

**Comment by James-the-Coding-Gamer** [comment]
20.04 10:34:51 [Server] Server thread/INFO [ViesCraft]: Logged in Server
20.04 10:34:51 [Server] Thread-45/INFO [chancecubes]: No custom rewards detected for the current user!
20.04 10:35:08 [Server] Vote-Listener/ERROR [votifier]: an error occured during decryption of data V???="K??@??=("???%???z?^\$? ?}B???,??qP^?(???#???)?????
20.04 10:35:08 [Server] INFO M????
20.04 10:35:08 [Server] INFO {i>.z?\#??j??>????`??M?|?????;i???MU?'7?????q???:?/V=?{p??-?,?????\L?/??;?-`?(??<Z???????$?.??7????"@? 7u?\$m??XQN; \<K?????&b[???^????!???????`e?~8???,4??VQ{RW
20.04 10:35:08 [Server] INFO M???(^i9?!????[o????[):cE?@9??z{?\Y??O7?:*n??????{?J????????m?|?+w?????|?=?
20.04 10:35:08 [Server] INFO javax.crypto.IllegalBlockSizeException: Data must not be longer than 256 bytes
20.04 10:35:08 [Server] INFO at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:344) ~[sunjce_provider.jar:1.8.0_201]
20.04 10:35:08 [Server] INFO at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) ~[sunjce_provider.jar:1.8.0_201]
20.04 10:35:08 [Server] INFO at javax.crypto.Cipher.doFinal(Cipher.java:2164) ~[?:1.8.0_201]
20.04 10:35:08 [Server] INFO at com.github.upcraftlp.votifier.util.RSAUtil.decrypt(RSAUtil.java:38) [RSAUtil.class:1.4.0]
20.04 10:35:08 [Server] INFO at com.github.upcraftlp.votifier.net.NetworkListenerThread.run(NetworkListenerThread.java:57) [NetworkListenerThread.class:1.4.0]
20.04 10:35:08 [Server] Vote-Listener/ERROR [votifier]: Votifier: incorrect vote received:
20.04 10:35:08 [Server] INFO -------

**Comment by zellfrey** [comment]
What version of forge votifier are you using?
What version of minecraft are you on?

**Comment by James-the-Coding-Gamer** [comment]
Mc 1.12.2 and forge-14.23.5.2838 and im useing voting-1.12.2-1.3.0

**Comment by zellfrey** [comment]
Please update to the latest version. IF the bug persists, come back to me.
Just curious, were you using ftbservers.com as a service for voting?

**Comment by James-the-Coding-Gamer** [comment]
no i was using a test https://minestatus.net/votifier/test i will update
and get back to you

**Comment by James-the-Coding-Gamer** [comment]
ok seems to be working now lol

21.04 11:31:26 [Server] Thread-46/INFO [chancecubes]: No custom rewards detected for the current user!
21.04 11:31:33 [Server] Server thread/INFO [votifier]: [1587483093221] received vote from realstonergamer (service: minestatus.net test vote)
21.04 11:31:33 [Server] Server thread/INFO [minecraft/DedicatedServer]: Set RealStonerGamer's game mode to Creative Mode
21.04 11:31:33 [Server] Server thread/INFO [minecraft/DedicatedServer]: Congratulations ?RealStonerGamer?!
21.04 11:31:33 [Server] Server thread/INFO [minecraft/DedicatedServer]: You just earned your daily reward!

**Comment by James-the-Coding-Gamer** [comment]
ok seems to be working now lol

21.04 11:31:26 [Server] Thread-46/INFO [chancecubes]: No custom rewards detected for the current user!
21.04 11:31:33 [Server] Server thread/INFO [votifier]: [1587483093221] received vote from realstonergamer (service: minestatus.net test vote)
21.04 11:31:33 [Server] Server thread/INFO [minecraft/DedicatedServer]: Set RealStonerGamer's game mode to Creative Mode
21.04 11:31:33 [Server] Server thread/INFO [minecraft/DedicatedServer]: Congratulations ?RealStonerGamer?!
21.04 11:31:33 [Server] Server thread/INFO [minecraft/DedicatedServer]: You just earned your daily reward!
